### files directory
samples: "samples.tsv"

### MAFFT parameters
mafft:
    ## choose algorithm
    algorithm: "--auto" # MSSPE parameter, default
    ## parameters
    op: 1.53 # default
    ep: 0.123 # default
    bl: 62 # default
    jtt: 62 # default
    tm: 62 # default
    fmodel: "off" # default
    ## outpet parameters
    clustalout: "off" # customized
    inputorder: "on" # default
    reorder: "off" # default
    treeout: "off" # default
    quiet: "off" # default
