dataDir: "/datater/wu/data"
refSeq : "/datater/wu/RefSeqProkaryota/RefSeqProkaryota.fna"

samples:
    enterovirus: "/datater/wu/data/enterovirus.fasta"
    # coronavirus: "/datater/wu/data/coronavirus.fasta"
    # zika : "/datater/wu/data/ZIKV-96seqs.fasta"

### multiple sequence aligment
mafft:
    # excution parameters
    threads: -1 # automatic
    ## choose algorithm
    algorithm: "--auto"
    ## parameters
    op: 1.53 # default
    ep: 0.123 # default
    bl: 62 # default
    jtt: 62 # default
    tm: 62 # default
    fmodel: "off" # default
    ## outpet parameters
    clustalout: "off" # customized
    inputorder: "on" # default
    reorder: "off" # default
    treeout: "off" # default
    quiet: "off" # default

### split overlapping chunks
step: 500
overlap: 250

### kmer counting
jellyfish:

### filtering
oligotm:
    monovalent-conc: 50 # unity mM
    divalent-conc: 0 # unity mM
    dNTP-conc: 0 # unity mM
    dna-conc: 50 # unity nM
    thermodynamic-para: 1
    salt-correlation: 1

mfeprimer:
    deltaG-cutoff : -9.0
    Tm-cutoff: 0
    score-cutoff: 5
    monovalent-conc: 50
    divalent-conc: 1.5
    dNTP-conc: 0.6
    oligo-conc: 50

### checkSpecifity

### heterodimer checking
