samples: "samples.tsv"
samples_dir: "test"
results_dir: "test/results"

# multiple sequence aligment ###################################################
mafft:
    # excution parameters
    threads: -1 # automatic
    ## choose algorithm
    algorithm: "--retree 1 --maxiterate 0 " # large dataset
    ## parameters
    op: 1.53 # default
    ep: 0.123 # default
    bl: 62 # default
    jtt: 62 # default
    tm: 62 # default
    fmodel: "off" # default
    ## outpet parameters
    clustalout: "off" # customized
    inputorder: "on" # default
    reorder: "off" # default
    treeout: "off" # default
    quiet: "off" # default

# split overlapping chunks #####################################################
step: 500
overlap: 250

# kmer counting ################################################################
dsk:
    nb-cores: 0 # default
    max-memory: 5000 # default
    max-disk: 0 # default
    out-compress: 0 # default
    storage-type: "hdf5" # default
    verbose: 1 # default
    kmer-size: 13 # default 31
    abundance-min: 2 # default
    abundance-max: 2147483647 # default
    abundance-min-threshold: 2 # default
    solidity-kind: "sum" # default
    solidity-custom: "" # default
    solid-kmers-out: "" # default
    # histogram parameters
    histo-max: 10000 # default
    histo2D: 0 # default
    histo: 0 # default

kmc3:
    kmer-size: 31
    ram: 25
    signature: 9
    input-format: "fasta"
    min-kmer-number: 2
    max-kmer-number: 255
    max-exclu-kmer: 1e9
    transformation: "on"
    ram-only: "off"
    # binNumber:
    threads: 8
    fq-read-threads: 8
    split-threads: 8
    second-stage-threads: 8
    file-name: ""
    output: "on"

gerbil:
    kmer-size: 31
    minimizer-length: "auto"
    max-memory: "auto" # or specify a number with MB/GB
    output-format: "fasta"
    threads: "auto" # or specify a number
    min-kmer-number: 3
    debug: "off"
    enable-gpu: "off"
    kmer-normalization: "off"
    stop-at-stage-one: "off"
    only-stage-two: "off"
    tmp-files-save: "off"
    histogram: "off"
