dataDir: "/datater/wu/data"
refSeq : "/datater/wu/RefSeqProkaryota/RefSeqProkaryota.fna"

samples:
    # enterovirus: "/datater/wu/data/enterovirus.fasta"
    coronavirus: "/datater/wu/data/coronavirus.fasta"
    # zika : "/datater/wu/data/ZIKV-96seqs.fasta"

### clustering
clustering: "True"
cd-hit:
    identity: 0.99
    thread: 8
    memory: 16000

### multiple sequence aligment
mafft:
    # excution parameters
    threads: -1 # automatic
    ## choose algorithm
    algorithm: "--auto"
    ## parameters
    op: 1.53 # default
    ep: 0.123 # default
    bl: 62 # default
    jtt: 62 # default
    tm: 62 # default
    fmodel: "off" # default
    ## outpet parameters
    clustalout: "off" # customized
    inputorder: "on" # default
    reorder: "off" # default
    treeout: "off" # default
    quiet: "off" # default

### split overlapping chunks
step: 500
overlap: 250

### kmer counting
jellyfish-count:
    kmer-size: 13
    hash-size: 100M
    thread: 1

### filtering $ dimer
oligotm:
    monovalent-conc: 50 # unity mM
    divalent-conc: 0 # unity mM
    dNTP-conc: 0 # unity mM
    dna-conc: 50 # unity nM
    thermodynamic-para: 1
    salt-correlation: 1

dimer-deltaG: -9000 # value inferior than this one will be eliminated

GC-upper: 40 # inferir than this value will be eliminated
GC-lower: 60  # superior than this value will be eliminated

LC: 0.75 # inferior than this value will be eliminated

### checkSpecifity
blast:
    evalue: 10
    word-size: 7
    max-target-seqs: 500
