#!/usr/bin/env python3.8
import os

configfile: "config-basic.yaml"

samples = list(config["samples"].keys())
refSeq = config["refSeq"]
taxID = config["taxID"]
taxLineage = config["taxLineage"]

dataDir = config["dataDir"]
refSeqFile = os.path.splitext(refSeq)[0]

kmerSize = config["jellyfish"]["kmer-size"]

def fetchConfigParameters():
    if config["mafft"]["fmodel"] == "on":
        config["mafft"]["fmodel"] = "--fmodel"
    else:
        config["mafft"]["fmodel"] = ""

    if config["mafft"]["clustalout"] == "on":
        config["mafft"]["clustalout"] = "--clustalout"
    else:
        config["mafft"]["clustalout"] = ""

    if config["mafft"]["inputorder"] == "on":
        config["mafft"]["inputorder"] = "--inputorder"
    else :
        config["mafft"]["inputorder"] = ""

    if config["mafft"]["reorder"] == "on":
        config["mafft"]["reorder"] = "--reorder"
    else:
        config["mafft"]["reorder"] = ""

    if config["mafft"]["treeout"] == "on":
        config["mafft"]["treeout"] = "--treeout"
    else :
        config["mafft"]["treeout"] = ""

    if config["mafft"]["quiet"] == "on":
        config["mafft"]["quiet"] = "--quiet"
    else:
        config["mafft"]["quiet"] = ""
fetchConfigParameters()


# def aggregate_input(wildcards):
#     checkpoint_output = checkpoints.splitFiles.get(**wildcards).output[0]
#     return expand(f"{dataDir}/{{sample}}/filtering/reverse{{seg}}.calculated2.filtered",
#                   sample = wildcards.sample,
#                   seg = glob_wildcards(os.path.join(checkpoint_output, "reverse{seg}.fasta")).seg)

rule all:
    input:
        expand(
            f"{dataDir}/{{sample}}/{{sample}}.uniq",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/{{sample}}.msa",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/allKmercount.sorted.calculated.txt",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/allKmerCount.sorted.calculated.filtered.txt",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/intermediate/allKmerCount.sorted.calculated.filtered.fasta",
            sample = samples
        ),
        expand(
            f"{refSeqFile}.DB.{{ext}}",
            sample = samples,
            ext = ["1.ebwt", "2.ebwt", "3.ebwt", "4.ebwt", "rev.1.ebwt", "rev.2.ebwt"]
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/intermediate/allKmerCount.sorted.calculated.filtered.bowtie",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/allKmerCount.sorted.calculated.filtered.spec.txt",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/allOligo.set",
            sample = samples
        ),
        ### EVALUATION
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/intermediate/aceID-taxID-species.tsv",
            sample = samples
        ),
        expand(
            f"{dataDir}/{{sample}}/kmer{kmerSize}/intermediate/allOligos_reverse.set.coverage",
            sample = samples
        )


include: "rules-basic/all_preprocessing.smk"
include: "rules-basic/reverse_kmer_kmerCount.smk"
include: "rules-basic/reverse_kmer_filter.smk"
include: "rules-basic/reverse_kmer_spec.smk"
include: "rules-basic/reverse_kmer_dimer.smk"
include: "rules-basic/all_evaluation.smk"
